### ISSUE TITLE
Dexter requires inverted envelopes

### ISSUE THREAD

**Issue by darloth** [ValleyAudio/ValleyRackFree#17]
Is this an issue, or just a quirk?  I don't know!

I did find it very odd that there's no direct way to modulate the level of a given operator with an envelope though - you have to invert them and use the attenuvertor fully negative, rather than a connected CV zeroing the level until the attenuvertor is positive, and I did not expect them to work that way.

I can feed the output through a VCA no problem, but I often want to apply envelopes to the operators themselves to change the time domain behaviour of the FM synthesis.

So I think in the end this is a feature request - could one (or both for consistency?) of the Level CV-ins for each operator be a direct multiplier please, such that you could connect an envelope or other CV and have it modulate the level from 0 at CV +0, to 1 at CV +10?

(Please feel free to point out if I'm just doing it wrong)

**Comment by ValleyAudio** [comment]
Any CV input is summed with whatever control is associated with it e.g. Operator Level = "Level Knob" + "Level CV" * "Level CV Attenuator". So really the level parameter is an offset of level rather than a master level control that just shuts off an operator even if there's CV.

This is to keep it consistent with VCF modulation, for example, where the cutoff knob offsets any CV modulation, so if the cutoff is at 0 then 10V CV would fully open the the filter and 0V would fully close it.

**Comment by ValleyAudio** [comment]
This is also how Akemie's Castle works by the way so I was also trying to be consistent with that module.

**Comment by ValleyAudio** [comment]
Furthermore there is space for me make a "Misc" page in the settings menu that could accommodate this feature as it does sound useful. I'm trying not to just throw everything into the right click menu you see.

**Comment by ValleyAudio** [comment]
@darloth okay so I've give it some thought. I can see how your requested feature would be useful, since you don't want to have to use VCAs or other external  modules to achieve it.

The quickest way I can implement it is to add a "master level" destination option to the Assignable Modulation inputs, and in the manual clearly indicate that the usual level control is an offset, not a global level. How does this sound to you?

**Comment by darloth** [comment]
That would seem usable and pefectly acceptable to me.  If that's an easy way to implement it and you think it's a good idea, go for it!

**Comment by gentleclockdivider** [comment]
Why is it called dexter , any resemblance to the dx is imho wrong  ?
It's not doing phase modulation , but pure log .pitch modulation .
You can clearly see this on the scope when doing operator feedback on itself .
Phase modulation , operator self feedback gives us a clear saw .

**Comment by ValleyAudio** [comment]
@gentleclockdivider Apologies for the late reply. Yeah it's a reference to the DX7 and friends, but is not an emulation of those synths. 

So you're saying that Dexter is or is not doing phase modulation? And that it doesn't give the saw wave when operator feedback is turned up? 

Bear in mind this parameter allows for destructive feedback when pushed too far.
