### ISSUE TITLE
ext sync topograph 0.6.5

### ISSUE THREAD

**Issue by NRG70** [ValleyAudio/ValleyRackFree#20]
i can't get Topograph to lock to ext sync anymore?
version 0.6.5
![topograph](https://user-images.githubusercontent.com/40998416/42641704-6ecf32de-85f5-11e8-9a23-cb2b3e3e6923.jpg)

**Comment by ValleyAudio** [comment]
Turn the blue dial fully left if you want it to be external clocked.

**Comment by NRG70** [comment]
oooops!! got it, thanks mister!

**Comment by NRG70** [comment]
hmmm, have to open the issue again. 
i did that turned all to the left. it runs, but it plays just a very very few triggers. 
As soon as i turn it to its own clock to the tempo value, it starts doing what it should do.
Even at lowest 4ppqn , BPM clock from AS or Clocked can not get it to go as when it is not externally synced.
I have to give it a clock that is multiplied by 2 or 3 before it starts to do something.
And then still it sounds different then when running on its own clock. 
Am missing something? 
Maybe i am doing something wrong?

**Comment by MarcBoule** [comment]
You need to multiply the clock by 4 since in its default mode, Topograph expects 4 PulsePerQuarterNote. 

But for the sounding different part, I am noticing something strange also. Here is my test with Topograph clocked external vs internal:

I tried AS BPM clock at 120BPM, using the 16ths output, which is the same as using Clocked's channel 1 at 120BPM with a ratio of X4, and those two behave exactly the same with Topograph, but then when you try the internal BPM on Topograph at 120BPM, it sounds different. Might be a bug in Topograph... or perhaps we are doing something incorrectly.

**Comment by ValleyAudio** [comment]
I cannot seem to replicate this problem. You are correct in using either using a x4 multiplier on clocked or the 16ths on AS with Topograph at 4 PPQN. With either an external 120 BPM, 4PPQN clock or Topographs own clock at 120 BPM, the patterns are at the same speed.

Is the problem perhaps missing steps when the density of a given channel is high?

**Comment by MarcBoule** [comment]
Thanks for the speedy response Dale. Just tried it, and that is indeed the case: I have the density of the 3rd channel at its maximum settting. When I try with a lower density, it sounds the same in all cases.
![image](https://user-images.githubusercontent.com/33604154/42653970-0e5088fa-85e5-11e8-8780-2a4b41e01dd8.png)

**Comment by ValleyAudio** [comment]
Okay, this is normal. This is actually what happens in the real life Grids module. At 4 PPQN, the shortest note that can be played is a 16th, or semi-quaver. However, the the drum patterns are in fact stored with 24 PPQN resolution which allows for 96th notes and triplets as 24 PPQN is a multiple of 3.

 So the reason why notes are being missed is that at 4 PPQN, Topograph / Grids has to advance it's step counter to the next nearest 16th note, essentially advancing 6 times per clock rather than once to compensate for the lower resolution and to stay in time. This then misses all of the notes that are in between the previous and the next 16th note. You can verify this by clocking Topograph with a clock multiplied either by x4, x8 or x24

**Comment by MarcBoule** [comment]
Ah, ok, I tried at 24 it's not missing anything. We should have RTFM: "4 and 8 PPQN modes can distort certain patterns" :-)
