### ISSUE TITLE
Topography external clock divides by 96

### ISSUE THREAD

**Issue by dataphreak1001** [ValleyAudio/ValleyRackFree#21]
Using an external clock on topography divides the number of beats by 96. If this is not correctable, the issue could be resolved by providing a master clock out. Sometimes, you just want 4 on the floor, you know...

**Comment by ValleyAudio** [comment]
@dataphreak1001 What resolution clock were you clocking Topograph with? If it is 1 clock per quarter note, then yeah it will divide by 96 because the patterns are arranged to be 24 ticks per beats, which incidentally is 4 times less 96. This is exact same behaviour as Grids.

To run topograph at the correct speed, supply a clock with either 4, 8 or 24 pulses per quarter note or beat (PPQN) resolution , and in the context menu check that topograph is dividing the external clock with the correct resolution. A 24PPQN will be the best because this also ensures the pattern isn't truncated.

**Comment by dataphreak1001** [comment]
Wooooow. I can't believe I missed that. Now that I know that's there, I can make this work. Do you think it's possible to add an option for 16ppqn? Most clocks will output 1/16 as the fastest iteration.

**Comment by ValleyAudio** [comment]
Yeah I can put that down on my todo list as 16ppqn can be divided further by two by Topograph to allow it to work with the existing 8ppqn option. Have you tried using Impromptu's Clocked module at all? That goes to 24x and would allow for untruncated patterns in 24ppqn mode.

**Comment by dataphreak1001** [comment]
I'll give it a look next time I fire up VCV. The math just doesn't work out for me is all. Almost everything I do is 4/4 time, and the closes to a classic time signature I can come up with for those numbers is a waltz.

**Comment by dataphreak1001** [comment]
What about an absolute mode, where the clock being input is just 1 pulse per quarter note?

**Comment by ValleyAudio** [comment]
@dataphreak1001 Apologies for the late reply.
A 1PPQN or "tap tempo" mode is on the cards as a few other people have requested this, so that'll be implemented probably in the next update.

**Comment by jponsford** [comment]
Hey, do you know of any other (smaller, less CPU) clocks that can output 24ppqn, besides Impromptu's Clocked? I'm using all three of Clocked's clocks in this patch, and it'd be nice to not have to use a second Clocked.

**Comment by ValleyAudio** [comment]
@jponsford The mscHack Master Clock module can output 24ppqn. It seems to use less cpu, though I'm running Rack on a high spec computer so the CPU usage difference between Clocked and Master Clock seems quite small.

**Comment by tacoe** [comment]
Came here because Topograph's trig out was consistently lagging a bit behind the master clock, which I had set to X24 to feed Topograph (after setting the tempo knob all the way to the left... rtfm 🤦‍♀️). Setting it to X4 (and using the context menu of topograph to set that to x4 as well) completely solved the issue. Still don't know if it's caused by Impromptu Clocked or by Topograph btw.
